name: Collect Streams Every 8 Hours

on:
  schedule:
    - cron: '0 */8 * * *'    # Her 8 saatte bir (0. saatte, 8. saatte, 16. saatte)
  workflow_dispatch:          # Manuel çalıştırma butonu
  push:                       # Kod değiştiğinde de test et
    paths:
      - 'collector.py'

jobs:
  collect-streams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests beautifulsoup4
        
    - name: Run Collector Script
      run: python collector.py
        
    - name: Commit and Push if Changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add streams.m3u
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update streams.m3u [$(date +'%Y-%m-%d %H:%M')]"
          git push
        fi